#include <iostream>
    
using namespace std;   

main () {                                                                                                                                                          

                                                                                                           
    cout <<"                                              :i368Q8g$g$$06MVr:`\n";                                                                                               
    cout <<"                                         -c$BBBQQQ88g00DEOOdZMHP3KUcr-\n";                                                                                          
    cout <<"                                      ,KB###BQQQ8g$DDEOMdMqPmmeIjzVc}}]]!\n";                                                                                       
    cout <<"                                    I#######QQg$$0ER6OdMPmeIjkykzVTYx\\r**;`\n";                                                                                    
    cout <<"                                 VB#######BQgE66OdOZMqPUIzyVc}L}]LiYv*^*<==!=!\n";                                                                                  
    cout <<"                               `M#####QQ8g0ER6OdOMqmIXXyulu}Yx]Lx)r*)r^;=!,__--\n";                                                                                 
    cout <<"                              ?QB#@@BQ888$$000DOq3GmXVuTYx]xxx/x?**<!'!:,,--````\n";                                                                               
    cout <<"                             IQB#@@@#Qg$06666RdGHqqjyT}ixv??\*rr**^<;:..,.``\n";                                                                                    
    cout <<"                            MggB####B8g$RdMqMGMdOdMIVLxxv**^^^;~~!!!:__  .\n";                                                                                      
    cout <<"                           yR00c.  _*lyKqMqqPKqMdMGPITYxr^!<~===!:'',-`\n";                                                                                          
    cout <<"                          ^6OD)        __:*TKdZqqMdMezu})r^~=~!:--..`\n";                                                                                           
    cout <<"                          dZOV`       !}l?=-_<xVUKqHmyuuux*;:':_.``\n";                                                                                             
    cout <<"                         XHOq^      `ieqdDDEZy)'`-,!<^)xYuT?<:,-``\n";                                                                                              
    cout <<"                         Gmdq=     `uZ6E0g888$0Omx=`  `-'*]uL*!-'\n";                                                                                               
    cout <<"                        `HGPj_     lM6D0gQQQQ8$DdGKcr'`   `:*ix<,`\n";                                                                                             
    cout <<"                        'Gm}^`    xHMdR0g8QQQQ80DEOPX}v^,`   -*x*'\n";                                                                                              
    cout <<"                        ,Gy=-    <KqMOR$QQQB##Q88QQ8$63L=-      !r^`\n";                                                                                            
    cout <<"                         ML_     zHHMOD8BB#########OV)!.'rL}})_   -~_\n";                                                                                           
    cout <<"                         j*`    ^eKPd$8B#BBB#BQg0OX/xY}XddMezyl/'   '_\n";                                                                                          
    cout <<"                         :!    ,yHqZDQQQQQ8g88g6GPGqGHHPUIyxr*rv]r_   '\n";                                                                                         
    cout <<"                         `_    ':~;*]kHd08QQ8$$6MMq3m}~=x        `::-\n";                                                                                          
    cout <<"                          _   *eqqMZdOE00$g88$$Eqeyu}! xqc_,=*)*^)}cT).                        `\n";                                                               
    cout <<"                          -   GE0Z3Vx**iIqZdR00OmuxuT!!x}yePejVyUKPGPUV^\n";                                                                                    
    cout <<"                          -   PEP:!r     rUzzqMKux)xT}x)?]uVkXmGMMHPHGHUi`\n";                                                                                      
    cout <<"                          `   ue- -x*_!*r\yc}zIVv?xvxilkzzIKqZO0$EdZMGMG3y_                       !`\n";                                                            
    cout <<"                              :]iPddOdmc}cyTTyjy}]YuuVXGdOddO0g8Q80E6dddZGj;                      `-.\n";                                                           
    cout <<"                              ~Zdddq3emImPmkyKqIylLY}}lIMOE0QBBBBQ88g0E6OMPX?\n";                                                                                   
    cout <<"                              ;6ddOdZMZO6dmPQ@@#0ITx?))iXd0Q#####BQQQ$0ROMH3q}                        `_!_\n";                                                      
    cout <<"                              ,8gQBBBQQQ$OM#@@@@@QOuLi\~.*H6gBBBBQQ88$DOdZZddqk                         _;~`\n";                                                    
    cout <<"                               O#@@@@@##8dB@@@@@@Q6MdMHX<'mOORDgQQQ8gD6dMZdddMMr                         `=;;`\n";                                                  
    cout <<"                               ;@@@@@@#QEM#@####Q0qHZMHzrL3GMG3IIImdOdMMqqZdOdZu                           :<^^-\n";                                                
    cout <<"                                Z@@@@#B8ORgB0yM8gRMdMmIjjzyyyyVucT))3ddZMqdOdM3)                           `^**?r\n";                                               
    cout <<"                                '@@@###$dRg0OPmmHMOROd3IjycTx?*:  !xU6OdqMdZM3c`                           -;^*?)*`\n";                                             
    cout <<"                                 0####QZcqEO6dem3ZOOdMITVulKi]* `*YumOZqPGqqmc:                           -!!=~**^^\n";                                             
    cout <<"                                ,EB###Qd*rKXY\*qD0QQ$##Q@@gdx--rlyXX3qmXImek}!                            ___,!^^^**-\n";                                           
    cout <<"                               r$Dg###B8M\\r:  _Q@@@@@@@Gm\!<]zKHPPHGmkVccTv_                           ``  ``_!;^*^*!\n";                                          
    cout <<"                              `0D6$$g##BQ0MIUeuux^)ejIXyXeeGMd6OdqqqMKk}i?:                                   .~r?xxr=!`\n";                                        
    cout <<"                              Y6ZRg$6MRQBB8066OQ0OEDE000$ggDERE6dZMGHX}\*`                                    ,*\?/xv^!!:\n";                                       
    cout <<"                              MdOO$gOHUzTVRQ8g$Q##BBBQg$gg$$$$D66OMPml*-                                    `-~**rxx)^~!~~,\n";                                     
    cout <<"                             ~dOOO$g0d3Kc_ :jQQQ###BQQ$$ggQQQg0DRMPmy=                                     `'!!^*xx)^~=~<;<*\n";                                    
    cout <<"                             OOOOO0g0OMPUx-  .yQB#@##BQQQ88880REMImV,                                     `':!!^)\]]]vr*r)*<< \n";                                
    cout <<"                            :BOO6d0g0OPUjT~`   'K#####QQ8gg$066PTV*                                       ::!^)x]}}lTYx)**^~:!`\n";                                 
    cout <<"                           _@BE6OM0$RdHjVl*.```  :yB##BQQ888DOUr_                                         ,~rv]i]ix?r*r:______:,\n";                                
    cout <<"                          *@@#gR6MO$DdHIyT]=` `'`` ,)jOgg$$OV~                                            !^rr))?LVyu}\~:,-.`  `_\n";                               
    cout <<"                         !@@@@B$DdO$6dMmyYv^-   ``````  ``                                               ,~)]cykVL*!-`'_':!!:-````\n";                              
    cout <<"                        *@@@@@B86mPg6OMmT)~:_`                                                          '*YVylr'           `-!:~~_'\n";                             
    cout <<"                       <@@@@@@#0qzI066Gyx=',_-`                                                       -^xcl\-        `.'.'`.--,^*!,'`\n";                           
    cout <<"                       @@@@@@@#6U}TOMMPkv'.`'__``                                                    ~r]cv          _!!=~!!=;;~~~=_' `\n";                          
    cout <<"                      Q@@@@@@@#djxvMMHKur_` `.__.`                                                 .^)v)-        `'^^^*^^<;~~;~!:_'`   `\n";                        
    cout <<"                     -@@@@@@@@@$HyVMM3XT),` ``-:,-'                                                !r;`      `:*r***r**^^^^~!:_-`       ``\n";                      
    cout <<"                     $@@@@@@@@@8MTrVZPj}):'```-!~~:_                                              `!'     :)v)r)r*^*;~!:,_-'`             `\n";                     
    cout <<"                     @@@@@@@@@@O]~:)Gey}?=_.``'_~*^!-                                             `     !?x?)))r~'`                         `\n";                   
    cout <<"                     @@@@@@@@@@R)!:;IjVLx<_```.'~)?:-`                                               .*x]x\)^,\n";                                               
    cout <<"                     @@@@@@@@@@8x^==cXVux^:-``.,!^r!`                                               !*)]x)~.       '..``\n";                                        
    cout <<"                     @@@@@@@@@@@q*<*}eV}x*!,__-_:~<^'`                                            `!^))r~-         `-,::_`\n";                                      
    cout <<"                    x@@@@@@@@@@@EiLYxVVlLr=:,-..,!^r^:-.`                                        .~^r*!.    `;;:!\lykkV])^!-                       `\n";            
    cout <<"                    #@@@@@@@@@@@@UXTvYkuLv*!_--.-:;r^:_-`                                       .,:=:.    !lcuyKMMddZqezkVu?~!'_-                  `-\n";           
    cout <<"                   }@@@@@@@@@@@@@UuLxxzuTL\^:,...-!*^~:.`                                       .-.`    -]kIq66OOOOddMH3mUXVVLxLu-\n";                             
    cout <<"                  ,@@@@@@@@@@@@@@Ol}}TkVY]x*=:----:^^^=_-`                                      `     `]jKD0gBB06OdZZMGHPHKUmIXPI! \n";                             
    cout <<"                 ;@@@@@@@@@@@@@@@@dUXkXV]xx?^!,_--_!~;!,-`                                           =jZ0gB@@@QDOdZO088RddGqGGMdG};\n";                             
    cout <<"                 Q@@@@@@@@@@@@@@@@OXqH3elx))r*;!,_'!;<!_-`                                          k08B@@@@B$DRQ@@@@@@#OZddZd6OMjyx``\n";                          
    cout <<"                .@@@@@@@@@@@@@@@@@#*XMHHyYx)rr^!:::,!~:_-`   ``                                   ,0##@@@@#8$0Q@@@@@@@@gdZdOOEDOHVxyTu:\n";                         
    cout <<"                @@@@@@@@@@@@##@@@@@qLI3HX}xr<=~!!'_,,,,_.   `-  ```````                          V#@@@@@#Qg8#@@@@@@@@@#OdO6OE$OqVLxxV|\n";                         
    cout <<"               #@@@@@@@@@@@@@@@@@@@@zePMP}\*!:____.-'.'..  -:` .',----`                         M#@@@@#Q8B@@@@@@@@@@@#$OORRR$$ZjxYTTT)*\n";                         
    cout <<"               @@@@@@@@@@@@@@@@@@#@@63dOMjT*:` ``--```-_,'!:'__,_--:,`                         H#@@@@B#@@@@@@@@@@@@@#gEO6EED$R3xxTlcyy*\n";                         
    cout <<"              g@@@@@@@@@@@@@@@@@@@##Qe6DOMI?:`   ``` `_:':;<!::,..--`                         ]@@@@#@@@@@@@@@@@@@@@#QE66D0D00MV)]VyjXU)\n";                         
    cout <<"             _@@@@@@@@@@@@@@@@@@@@@@@$OEOdGv=,-_,'   -,~)r^~!!:,.'`                          ,@@@@@@@@@@@@@@@@@@@##Q0R66D0Dg6Ix)TzjUHG-\n";                        
    cout <<"             m@@@@@@@@@@@@@@@@@@@@@@@@8ZORdc?xv\)^:,_=)ixr^;~=!:_-                          l@@@@@@@@@@@@@@@@@@@@@#$R6RED0$$q]rxcemqG-\n";                         
    cout <<"             #@@@@@@@@@@@BDE$Q##@@@@@@@U}MMdEeulyc}x/xi\p\irr*;:-                          K@@@@@@@@@@@@@@@@@@@@@#gRRREDD0$6V^rcXGmd`\n";                          
    cout <<"             #@@@@@@@@@@@@@#DVrr]yH$##0muVZyVKmqL*^,,,,,'~rv)~_`                          ~@@@@@@@@@@@@@@@@@@@@@@QEO6RDD0$gqr=xjqGPG\n";                          
    cout <<"             @@@@@@#@@@@#QQ#@@@I_.,^xyjVTvcur~~):````                                     d@@@@@@@@@@@@@@@@@@@@@BROO6E00$g$V~^uqOqOT\n";                           
    cout <<"            `@@@@@@@@@@@@@@@@@@@B``-_~\}\      ````                                       #@@@@@@@@@@@@@@@@@@@@@0R0DED00$8q*!xUROdj\n";                           
    cout <<"            !@@@@@@@@@@@@@@@@@@@@H  `._~^         `                                      K@@@@@@@@@@@@@@@@@@@@@BgQgDERD$gRx,)yO$DEx\n";                          
    cout <<"            `@@@@@@@@@@@@@@@@@@@@@V  ``-,       .                                      .@@@@##@@@@@@@@@@@@@@@@#QBQ$RE6E$gV!'lM006RO_\n";                        
    cout <<"             @@@@@@@@@@@@@@@@@@@@@#~  `''`                                            *@@#B#@@@@@@@@@@@@@@@@@@##B8E6RRD$H;-*eED3jGqGk*`\n";        
}
